### ISSUE TITLE
Support for well-known payees

### ISSUE THREAD

**Issue by DamienCassou** [cantino/reckon#135]
A ledger transaction entry starts with a date and a payee, e.g.,

```ledger
2025/06/07 biocoop
    asset:current:couple                     -100
    expense:food:daily                        100
```

In this case, "biocoop" is the payee.

For years, I've been maintaining a file in which I associate regular expressions matching bank transaction's descriptions to well-known payees, e.g.,

```yaml
biocoop:
  - BIOCOOP
  - KERBIO
  - SA FINIS TERRA
  - COGIBIO
  - VILLENAVE BIO
  - BIOMEN

filling station:
  - ESSO
  - SA STEREN
  - LECLERC STATIO
  - LECLERC ESSENC
  - BLENAN DAC
...
```

The same way reckon uses account tokens to find the proper accounts, could it also find the proper payee?
